const BAD_REQUEST_STATUS_CODE = 400;
const NOT_FOUND_STATUS_CODE = 404;
const INTERNAL_SERVER_ERROR_STATUS_CODE = 500;
const CREATED_STATUS_CODE = 201;
const OK_STATUS_CODE = 200;

module.exports = {
BAD_REQUEST_STATUS_CODE,
NOT_FOUND_STATUS_CODE,
INTERNAL_SERVER_ERROR_STATUS_CODE,
CREATED_STATUS_CODE,
OK_STATUS_CODE
}